99 Add serializer for std::unique_ptr
DARMA-tasking/checkpoint pull request #100
Opened 2020-05-14 19:33 UTC by lifflander

Fixes #99

2020-05-14 21:29 UTC, PhilMiller commented
I could swear we had this in there already. Maybe in the wrong file or something?

2020-05-15 15:47 UTC, PhilMiller commented
OK, I was thinking of the identical logic in `serializeRCP` I guess

2020-05-15 15:52 UTC, PhilMiller commented on src/checkpoint/container/unique_ptr_serialize.h
> +      auto t = std::allocator<T>{}.allocate(1);
If we want to be *really* paranoid, we could add an assertion here that `alignof(T) <= __STDCPP_DEFAULT_NEW_ALIGNMENT__`

2020-05-15 15:53 UTC, PhilMiller commented on src/checkpoint/container/unique_ptr_serialize.h
> +      auto t = std::allocator<T>{}.allocate(1);
`static_assert` would be nice, but I'm not sure if that would run into SFINAE issues in this circumstance

2020-05-15 15:55 UTC, PhilMiller approved these changes

2020-05-19 14:56 UTC, PhilMiller requested changes

2020-05-19 14:56 UTC, PhilMiller commented on src/checkpoint/container/unique_ptr_serialize.h
> +      auto t = std::allocator<T>{}.allocate(1);
I think this allocation and reconstruction logic is likely duplicative of something that should be in functions called by `dispatch::deserialize` already. Let's make sure we get it right there, and then just call the same thing.

2020-05-20 00:49 UTC, lifflander commented
@PhilMiller I've abstracted out allocation into `dispatch::Standard::allocate<T>`. I can't combine this with reconstruction easily. And we can't call into the API that returns a unique_ptr because that's only on the unpacking side.

2020-05-20 19:58 UTC, merged