#203 track and check memory usage during serialization
DARMA-tasking/checkpoint pull request #208
Opened 2021-05-13 15:11 UTC by jstrzebonski

Fixes #203 

As discussed on the weekly - the check is always active, and it's not recursive (yet).

2021-05-13 15:12 UTC, jstrzebonski commented
I'm not sure if the exceptions msges are good enough. If that's not the case I might need some help to improve them.

2021-05-13 17:42 UTC, jstrzebonski commented on src/checkpoint/dispatch/dispatch.impl.h
> +  #endif
That's somehow ugly but I don't see a better way of doing it correctly.

2021-05-13 17:49 UTC, jstrzebonski commented on src/checkpoint/dispatch/dispatch.impl.h
> +  #endif
Good thing is that if for any reason this calculation becomes invalid, most of the tests will fail.

2021-05-19 16:44 UTC, jstrzebonski commented
One thing to note is that nvcc-11 constantly fails. It seems that there might be a problem with resources on GitHub pipeline.

2021-05-25 15:26 UTC, PhilMiller commented
As noted by Codecov, the error cases are not covered by the tests. Could you write tests that intentionally serialize different payloads between sizing and packing, and between packing and unpacking, and assert that an exception of the right type is thrown?

2021-05-25 22:58 UTC, lifflander requested changes
Overall this looks good. I would like more testing to cover cases where the buffer is not properly sized and expect failure. Hopefully, that will get code coverage to complain less also. Additionally, I would like to add documentation about this check and the error that it throws and what it means.

2021-05-25 22:58 UTC, lifflander commented on tests/unit/test_sizer.cc
>  TEST_F(TestSizer, test_sizer_1) {
I don't think I see any tests that check for the failure case when the buffer size doesn't match. Could we construct that use case which would improve code coverage?

2021-05-29 17:57 UTC, jstrzebonski commented
@PhilMiller @lifflander 
I added missing unit tests. It's ready to re-review.

2021-05-29 19:42 UTC, PhilMiller approved these changes

2021-05-29 19:49 UTC, PhilMiller commented
I think the error message phrasing is quite good enough. If we wanted to be a bit more explicit, it could say "Check for a path mismatch in the associated `serialize` routine", and I think that would pretty much cover as much as any documentation that Jonathan was looking for would say.

2021-06-01 18:33 UTC, lifflander approved these changes

2021-06-01 18:34 UTC, merged

2021-06-01 18:35 UTC, lifflander commented
@jstrzebonski I've decided that the documentation of the error message is sufficient and thus merged this. We are waiting in EMPIRE for this to go through.