#264: Add serializers for kokkos types (1/2) - Kokkos::Pair
DARMA-tasking/checkpoint pull request #267
Opened 2022-10-24 14:42 UTC by thearusable

Relates to #264

2022-10-24 15:28 UTC, PhilMiller commented
These should be simple enough that you can just do it in one PR, and say this PR fixes the issue

2022-10-24 15:32 UTC, PhilMiller requested changes
The (de)serialization logic is way more complicated than I would have expected. Could you write a bit about why that's all necessary, and maybe add that motivation as comments in the code?

2022-10-25 11:05 UTC, thearusable commented
@PhilMiller Indeed! That could be accomplished in much simpler way. Thanks for catching that!

2022-10-25 17:30 UTC, PhilMiller approved these changes

2022-10-25 17:31 UTC, merged