#260: Add alias namespace
DARMA-tasking/checkpoint pull request #339
Opened 2024-05-20 11:10 UTC by thearusable

Closes #260

2024-05-20 21:41 UTC, cz4rs approved these changes
Looks good to me.

2024-05-21 16:49 UTC, lifflander requested changes

2024-05-21 16:49 UTC, lifflander commented on src/checkpoint/checkpoint.h
>  #endif /*INCLUDED_CHECKPOINT_CHECKPOINT_H*/
We should just the header guards to correspond to the namespace change.

2024-05-21 16:57 UTC, lifflander reviewed
Let's just add the alias the other way around.

2024-05-23 13:23 UTC, thearusable commented
I updated the implementation to not change the name of checkpoint namespace. I needed to rename the magistrate namespace in examples.

2024-05-28 16:34 UTC, lifflander approved these changes

2024-05-28 16:34 UTC, merged